name: Release
on:
  push:
    branches: [ main ]
permissions:
  contents: write
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Set Up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python
        run: uv python install
      - name: Install Dependencies
        run: uv sync --frozen --all-extras
      - name: Parse CHANGELOG.md
        id: changelog
        run: uv run parse_changelog.py
      - name: Check Tag
        id: tag
        run: |
          git fetch --tags --force

          if git rev-parse "v${{ steps.changelog.outputs.version }}" >/dev/null 2>&1; then
            echo ::error::"Tag v${{ steps.changelog.outputs.version }} already exists"

            exit 1
          fi
      - name: Tag
        run: |
          git tag "v${{ steps.changelog.outputs.version }}"
          git push origin "v${{ steps.changelog.outputs.version }}"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.changelog.outputs.version }}
          name: v${{ steps.changelog.outputs.version }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
      - name: Build
        run: uv run mkdocs build --strict
      - name: Deploy
        run: uv run mkdocs gh-deploy --force --message "Deploy v${{ steps.changelog.outputs.version }}"
